### ISSUE TITLE
Wrong tiers and incorrect probabilities.

### ISSUE THREAD

**Issue by zizouqi** [auto-chess-ui-mod/download#3]
![Picture 1](https://i.imgur.com/iAEXUmL.jpg)  

![Picture 2](https://i.imgur.com/4l9rMCS.png)  

I have Axe, Tinker, Batrider, BH and AM on my board and bench. 

The tier for each piece shows "?" and the numbers of pieces are incorrect in the first pic, the draw probability of Axe is wrong in the second pic.

**Comment by TiesdeKok** [comment]
Ah! I did not consider that, it matches everything based on the names because the code base of DAC is not very consistent with the identifiers. I'd have to include a conversation table for the Chinese names of the heroes, this is easy enough, but I would need to find the Chinese names in the source VPK. 

Thanks for the heads up, I'll look into it and let you know once I have a fixed version for you to try.

**Comment by zizouqi** [comment]
https://pastebin.com/Cp2V39Qg
Here is the pieces name translation, hope this help.

**Comment by TiesdeKok** [comment]
Awesome, that was very helpful! I have support for clients that use Chinese names, so feel free to try it out (it is already on github [changes](https://github.com/auto-chess-ui-mod/source/commit/f784c6e555e2519fb4c783c5dd0da6c25d3f33b7)) and let me know if you run into any other problems. Also, would you mind sharing where you posted it, would love to check it.

**Comment by zizouqi** [comment]
I've posted your UI mod in the following three places:
小黑盒： https://www.xiaoheihe.cn/community/57743/list/22025714
旅法师营地： https://www.iyingdi.com/web/bbspost/detail/1900079
My personal Weibo (Chinese version Twitter): https://weibo.com/ttarticle/p/show?id=2309404365097127543404
